version: 0.2

phases:
  install:
    commands:
      - echo "No dependencies to install"
  build:
    commands:
      - echo "Building PHP application..."
  post_build:
    commands:
      - echo "Build completed"

artifacts:
  files:
    - '**/*'
  discard-paths: no
